<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUtzuOJx\Glpi_Kernel_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUtzuOJx/Glpi_Kernel_KernelProductionContainer.php') {
    touch(__DIR__.'/ContainerUtzuOJx.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionContainer::class, false)) {
    \class_alias(\ContainerUtzuOJx\Glpi_Kernel_KernelProductionContainer::class, Glpi_Kernel_KernelProductionContainer::class, false);
}

return new \ContainerUtzuOJx\Glpi_Kernel_KernelProductionContainer([
    'container.build_hash' => 'UtzuOJx',
    'container.build_id' => 'ffcd81f1',
    'container.build_time' => 1764150362,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUtzuOJx');
